import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ToastProvider } from "@/components/ui/toast-provider";

import { TRPCReactProvider } from "@/trpc/react";
import SidebarMenu from "@/components/sidebar-menu/sidebar-menu";
import Navbar from "@/components/common/navbar";

export const metadata: Metadata = {
  title: "Near Yield",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex bg-background">
        <ToastProvider>
          <div className="min-h-screen w-64 bg-foreground">
            <SidebarMenu />
          </div>
          <main className="flex-1 overflow-y-auto bg-background p-6">
            <TRPCReactProvider>
              <Navbar />
              {children}
            </TRPCReactProvider>
          </main>
        </ToastProvider>
      </body>
    </html>
  );
}
